### ISSUE TITLE
请问怎么添加统计代码？

### ISSUE THREAD

**Issue by xfxx2022** [shengxinjing/email-helper#10]
我使用vercel搭建的
请问百度统计或者谷歌统计的代码，麻烦问问可以添加到哪里?
还有我的开发者模式Network里面 [_vercel/insights/script.js是红色的(Status Code: 404 )，也帮忙看看，谢谢。

**Comment by shengxinjing** [comment]
我直接用的vercel的analysis
https://vercel.com/docs/concepts/analytics/audiences/package
