### ISSUE TITLE
API key Rotated

### ISSUE THREAD

**Issue by BurtSweet** [shengxinjing/email-helper#13]
请教大佬,我fork了这个项目并部署.但是很快就收到了OpenAI的邮件提示API key泄漏并自动更新了后台的API key.这个您是如何解决的呢!

**Comment by zer0fire** [comment]
没记错的话，需要在根目录下的 `.env` 文件或者 `.env*.local` 里配置，你是怎么配置的？截个打码图看看

**Comment by BurtSweet** [comment]
我就是在根目录的.env里面写的key.但是马上邮件就提示我key暴露了并且强制刷新了key

**Comment by zhengbangbo** [comment]
> 我就是在根目录的.env里面写的key.但是马上邮件就提示我key暴露了并且强制刷新了key

https://github.com/BurtSweet/teach-anything/blob/main/.env 你不要把 .env 上传上来啊。gitignore 都挡不住你上传😅。

不管你用什么平台部署，都可以在在后台配置环境变量的，下面这个图是 vercel 的：

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/18254135/217408205-e5015e7c-3386-4b39-9b65-7d7371204926.png">

**Comment by BurtSweet** [comment]
感谢大佬,配置环境变量问题已经解决!
